version: "3.1"

volumes:
  site-estoque-db:
    driver: "local"

networks:
  site-estoque-network:
    driver: "bridge"

services:
  db:
    image: mysql:8.0
    container_name: site-estoque-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - site-estoque-db:/var/lib/mysql
    networks:
      - site-estoque-network

  app:
    build: .
    container_name: site-estoque-app
    tty: true
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - site-estoque-network
